### PR TITLE
Support zkevm chain

### PR DESCRIPTION
**Pull request by mohammadranjbarz**
related to #23

Cardona: https://www.notion.so/giveth/a521deb4b9604e3bbe56a90f8b6436d3?v=f5e880fc0c81457b974fb89fa7a01ba9
Mainnet: https://www.notion.so/giveth/641e512e33124a249177f67ba4762044?v=86ba47af2a9a4927a68cf0a8fcbe5c7d

### CODE REVIEW

**Comment by mohammadranjbarz** [comment]
> Is it a duplicate of #25?

Target branch of one of them is `staging`, the other one is `main`

**Comment by aminlatifi** [comment]
Hmm, isn't the convention to first merge to staging and them to main?!

**Comment by mohammadranjbarz** [comment]
> Hmm, isn't the convention to first merge to staging and then merge it to main?!

I didn't know the convention for this project, and staging had some commits that are not in the production, so I made two PRs for that

**Comment by aminlatifi** [comment]
> > Hmm, isn't the convention to first merge to staging and then merge it to main?!
> 
> I didn't know the convention for this project, and staging had some commits that are not in the production, so I made two PRs for that

The main and staging look like the same, few commits are difference that don't change any file. I suggest first merge to staging and merge that to main

**Comment by mohammadranjbarz** [comment]
> > > Hmm, isn't the convention to first merge to staging and then merge it to main?!
> > 
> > 
> > I didn't know the convention for this project, and staging had some commits that are not in the production, so I made two PRs for that
> 
> The main and staging look like the same, few commits are difference that don't change any file. I suggest first merge to staging and merge that to main

Cool I will do that

**Pull request merged**
